# nba-rating

Expected score of Team A:
$$E_A=\frac{1}{1+10^{(R_B-R_A)/400}}$$

Expected score of Team B:
$$E_B=\frac{1}{1+10^{(R_A-R_B)/400}}$$

These are also represented by: 
$$E_A=\frac{Q_A}{Q_A+Q_B}$$
$$E_B=\frac{Q_B}{Q_A+Q_B}$$


$Q_A=10^{R_A/400}$, $Q_B=10^{R_B/400}$

In [13]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from pathlib import Path
from datetime import datetime
import requests
import bs4
from NBARater import NBARater

In [15]:
# Script for scraping data
!python NBAScraper.py --beginning 1975 --end 2024

Scraping data for the 1975 to 2024 seasons...
Fetching 1975-1976 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1976-1977 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1977-1978 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1978-1979 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1979-1980 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1980-1981 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1981-1982 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1982-1983 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1983-1984 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1984-1985 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1985-1986 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1986-1987 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1987-1988 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1988-1989 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1989-1990 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1990-1991 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1991-1992 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1992-1993 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1993-1994 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1994-1995 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1995-1996 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1996-1997 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1997-1998 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1998-1999 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 1999-2000 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2000-2001 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2001-2002 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2002-2003 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2003-2004 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2004-2005 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2005-2006 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2006-2007 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2007-2008 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2008-2009 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2009-2010 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2010-2011 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2011-2012 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2012-2013 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2013-2014 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2014-2015 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2015-2016 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2016-2017 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2017-2018 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2018-2019 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2019-2020 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2020-2021 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2021-2022 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2022-2023 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2023-2024 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Fetching 2024-2025 season...
Loading: 100%|█████████████████████████████████| 35/35 [00:35<00:00,  1.00s/sec]
Data saved to: data/1975-2024.csv

In [ ]:
import sqlite3

conn = sqlite3.connect(Path('data') / 'nba.db')
df = pd.read_sql("""
    SELECT
        date            AS "Date",
        start_time      AS "Start Time (ET)",
        visitor         AS "Visitor",
        visitor_points  AS "Visitor Points",
        home            AS "Home",
        home_points     AS "Home Points",
        box_score       AS "Box Score",
        overtime        AS "Overtime",
        attendance      AS "Attendance",
        arena           AS "Arena",
        notes           AS "Notes"
    FROM games ORDER BY date
""", conn)
conn.close()
df

In [17]:
df[df['Notes'] == 'Playoffs']

,Date,Start Time (ET),Visitor,Visitor Points,Home,Home Points,Box Score,Overtime,Attendance,Arena,Notes
684,1976-05-02,NaN,Phoenix Suns,103,Golden State Warriors,128,https://www.basketball-reference.com//boxscore...,NaN,NaN,Oakland-Alameda County Coliseum Arena,Playoffs
685,1976-05-02,NaN,Boston Celtics,104,Buffalo Braves,100,https://www.basketball-reference.com//boxscore...,NaN,NaN,Buffalo Memorial Auditorium,Playoffs
686,1976-05-05,NaN,Phoenix Suns,108,Golden State Warriors,101,https://www.basketball-reference.com//boxscore...,NaN,NaN,Oakland-Alameda County Coliseum Arena,Playoffs
687,1976-05-06,NaN,Cleveland Cavaliers,99,Boston Celtics,111,https://www.basketball-reference.com//boxscore...,NaN,NaN,Boston Garden,Playoffs
688,1976-05-07,NaN,Golden State Warriors,99,Phoenix Suns,91,https://www.basketball-reference.com//boxscore...,NaN,NaN,Arizona Veterans Memorial Coliseum,Playoffs
...,...,...,...,...,...,...,...,...,...,...,...
18794,2023-06-01,8:30p,Miami Heat,93,Denver Nuggets,104,https://www.basketball-reference.com//boxscore...,NaN,"19,528",Ball Arena,Playoffs
18795,2023-06-04,8:00p,Miami Heat,111,Denver Nuggets,108,https://www.basketball-reference.com//boxscore...,NaN,"19,537",Ball Arena,Playoffs
18796,2023-06-07,8:30p,Denver Nuggets,109,Miami Heat,94,https://www.basketball-reference.com//boxscore...,NaN,"20,019",Kaseya Center,Playoffs
18797,2023-06-09,8:30p,Denver Nuggets,108,Miami Heat,95,https://www.basketball-reference.com//boxscore...,NaN,"20,184",Kaseya Center,Playoffs
18798,2023-06-12,8:30p,Miami Heat,89,Denver Nuggets,94,https://www.basketball-reference.com//boxscore...,NaN,"19,537",Ball Arena,Playoffs

In [18]:
df['Date'] = pd.to_datetime(df['Date'])
df['Win'] = np.where(df['Visitor Points'] > df['Home Points'], 1, np.where(df['Visitor Points'] < df['Home Points'], 0, 0.5))
df

,Date,Start Time (ET),Visitor,Visitor Points,Home,Home Points,Box Score,Overtime,Attendance,Arena,Notes,Win
0,1975-10-23,NaN,Golden State Warriors,89,Cleveland Cavaliers,83,https://www.basketball-reference.com//boxscore...,NaN,NaN,Coliseum at Richfield,NaN,1.0
1,1975-10-23,NaN,Los Angeles Lakers,104,New York Knicks,101,https://www.basketball-reference.com//boxscore...,NaN,NaN,Madison Square Garden (IV),NaN,1.0
2,1975-10-23,NaN,Kansas City Kings,95,Washington Bullets,107,https://www.basketball-reference.com//boxscore...,NaN,NaN,Capital Centre,NaN,0.0
3,1975-10-23,NaN,New Orleans Jazz,91,Atlanta Hawks,109,https://www.basketball-reference.com//boxscore...,NaN,NaN,Omni Coliseum,NaN,0.0
4,1975-10-24,NaN,Houston Rockets,94,Boston Celtics,109,https://www.basketball-reference.com//boxscore...,NaN,NaN,Boston Garden,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
19680,2024-02-29,7:30p,Golden State Warriors,110,New York Knicks,99,https://www.basketball-reference.com//boxscore...,NaN,"19,812",Madison Square Garden (IV),NaN,1.0
19681,2024-02-29,8:30p,Oklahoma City Thunder,118,San Antonio Spurs,132,https://www.basketball-reference.com//boxscore...,NaN,"18,392",Frost Bank Center,NaN,0.0
19682,2024-02-29,9:00p,Houston Rockets,105,Phoenix Suns,110,https://www.basketball-reference.com//boxscore...,NaN,"17,071",Footprint Center,NaN,0.0
19683,2024-02-29,10:00p,Miami Heat,97,Denver Nuggets,103,https://www.basketball-reference.com//boxscore...,NaN,"19,634",Ball Arena,NaN,0.0
19684,2024-02-29,10:30p,Washington Wizards,131,Los Angeles Lakers,134,https://www.basketball-reference.com//boxscore...,OT,"18,997",Crypto.com Arena,NaN,0.0

In [19]:
rating = NBARater()
rating.eloSimulator(df)

In [20]:
teams_elo = rating.getTeams()

In [21]:
# Create traces for each key
traces = []
for key, values in teams_elo.items():
    trace = go.Scatter(x=list(range(1, len(values) + 1)), y=values, mode='lines+markers', name=key)
    traces.append(trace)

# Create layout
layout = go.Layout(title='Interactive Line Plot', xaxis=dict(title='Index'), yaxis=dict(title='Values'))

# Create figure
fig = go.Figure(data=traces, layout=layout)

# Show the interactive plot
fig.show()

In [ ]:
latest_rating = {}
for key, value in teams_elo.items():
    latest_rating[key] = value[-1]
dict(sorted(latest_rating.items(), key=lambda item: item[1], reverse=True))

In [ ]:
import requests
import bs4

url = f'https://en.wikipedia.org/wiki/2020_NBA_playoffs'
response = requests.get(url)
response.raise_for_status()

soup = bs4.BeautifulSoup(response.text, 'lxml')
dates = (soup.find('body')
         .find('div', class_='mw-page-container')
         .find('div', class_='mw-page-container-inner')
         .find('div', class_='mw-content-container')
         .find('main', class_='mw-body')
         .find('div', class_='mw-body-content')
         .find('div', class_='mw-content-ltr mw-parser-output')
         .find('table', class_='infobox vcard')
         .find('tbody')
         .find_all('tr')[3]
         .find('td', class_='infobox-data')).text
dates

In [ ]:
date = dates.split(',')
date

In [ ]:
date[0].split('–')[0].strip()